"""add_feedback_fields_to_impact_and_report

Revision ID: 25ff3a21fe7e
Revises: eeaf3ad1511d
Create Date: 2026-07-29 17:04:13.617886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ff3a21fe7e'
down_revision: Union[str, Sequence[str], None] = 'eeaf3ad1511d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_impact_analysis', sa.Column('adopted', sa.Boolean(), nullable=True, comment='人工是否采纳（None=未反馈）'))
    op.add_column('ai_impact_analysis', sa.Column('feedback_comment', sa.Text(), nullable=True, comment='人工反馈备注'))
    op.add_column('ai_report_interpretations', sa.Column('session_id', sa.String(length=100), nullable=False, comment='会话 ID'))
    op.add_column('ai_report_interpretations', sa.Column('adopted', sa.Boolean(), nullable=True, comment='人工是否采纳（None=未反馈）'))
    op.add_column('ai_report_interpretations', sa.Column('feedback_comment', sa.Text(), nullable=True, comment='人工反馈备注'))
    op.create_index('ix_report_session', 'ai_report_interpretations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_session', table_name='ai_report_interpretations')
    op.drop_column('ai_report_interpretations', 'feedback_comment')
    op.drop_column('ai_report_interpretations', 'adopted')
    op.drop_column('ai_report_interpretations', 'session_id')
    op.drop_column('ai_impact_analysis', 'feedback_comment')
    op.drop_column('ai_impact_analysis', 'adopted')
    # ### end Alembic commands ###
