"""add_ai_dedup_links_and_feedback_comment

Revision ID: 5983b791b2be
Revises: e28f1f434097
Create Date: 2026-07-28 10:32:56.289032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5983b791b2be'
down_revision: Union[str, Sequence[str], None] = 'e28f1f434097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_dedup_links',
    sa.Column('source_issue_id', sa.BigInteger(), nullable=False, comment='源问题单 ID'),
    sa.Column('matched_issue_id', sa.BigInteger(), nullable=False, comment='被匹配的重复问题单 ID'),
    sa.Column('similarity', sa.Float(), nullable=False, comment='向量余弦相似度'),
    sa.Column('evidence', sa.String(length=50), nullable=False, comment='匹配证据：model_and_sw / dtc / model_and_sw+dtc'),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False, comment='是否判定为重复'),
    sa.Column('reviewed', sa.Boolean(), nullable=True, comment='人工复核结果（None=未复核）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['matched_issue_id'], ['alm_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['alm_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_issue_id', 'matched_issue_id', name='uq_dedup_link')
    )
    op.create_index('ix_dedup_matched', 'ai_dedup_links', ['matched_issue_id'], unique=False)
    op.create_index('ix_dedup_source', 'ai_dedup_links', ['source_issue_id'], unique=False)
    op.add_column('ai_triage_results', sa.Column('feedback_comment', sa.Text(), nullable=True, comment='人工反馈备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_triage_results', 'feedback_comment')
    op.drop_index('ix_dedup_source', table_name='ai_dedup_links')
    op.drop_index('ix_dedup_matched', table_name='ai_dedup_links')
    op.drop_table('ai_dedup_links')
    # ### end Alembic commands ###
