"""init alm 12 tables

Revision ID: 72d5a060be9c
Revises: 
Create Date: 2026-07-26 22:23:49.103323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d5a060be9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alm_baselines',
    sa.Column('baseline_no', sa.String(length=50), nullable=False, comment='基线编号，如 BL-EV-2025Q1'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='基线名称'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('is_frozen', sa.Boolean(), nullable=False, comment='是否已冻结'),
    sa.Column('freeze_date', sa.String(length=20), nullable=True, comment='冻结日期 YYYY-MM-DD'),
    sa.Column('release_date', sa.String(length=20), nullable=True, comment='计划发布日期 YYYY-MM-DD'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_no')
    )
    op.create_index('ix_alm_baseline_frozen', 'alm_baselines', ['is_frozen'], unique=False)
    op.create_table('alm_config_items',
    sa.Column('ci_no', sa.String(length=50), nullable=False, comment='配置项编号，如 CI-BMS-001'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='配置项名称，如 电池管理系统BMS'),
    sa.Column('alias', sa.String(length=500), nullable=True, comment='别名，逗号分隔（三层标准化第一层用）'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='类别：software/hardware/calibration/doc'),
    sa.Column('module', sa.String(length=100), nullable=True, comment='所属模块，用于基线冲突二级 module_match'),
    sa.Column('supplier', sa.String(length=200), nullable=True, comment='供应商'),
    sa.Column('part_number', sa.String(length=100), nullable=True, comment='零件号/软件件号'),
    sa.Column('sw_version', sa.String(length=50), nullable=True, comment='当前软件版本'),
    sa.Column('is_safety_related', sa.Boolean(), nullable=False, comment='是否功能安全相关（ISO 26262）'),
    sa.Column('lifecycle_status', sa.String(length=20), nullable=False, comment='生命周期：dev/active/frozen/obsolete'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci_no')
    )
    op.create_index('ix_alm_ci_module', 'alm_config_items', ['module'], unique=False)
    op.create_index('ix_alm_ci_safety', 'alm_config_items', ['is_safety_related'], unique=False)
    op.create_table('dtc_codes',
    sa.Column('code', sa.String(length=10), nullable=False, comment='故障码，如 P0A0F / U0155'),
    sa.Column('system', sa.String(length=30), nullable=False, comment='系统：powertrain/chassis/body/network'),
    sa.Column('description', sa.Text(), nullable=True, comment='英文原始描述'),
    sa.Column('description_zh', sa.Text(), nullable=True, comment='中文描述（LLM 批量翻译）'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线（码段规则映射，不过 LLM）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_dtc_line', 'dtc_codes', ['business_line'], unique=False)
    op.create_table('owner_domains',
    sa.Column('name', sa.String(length=100), nullable=False, comment='责任域名称，如：电池系统域'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('description', sa.Text(), nullable=True, comment='职责范围'),
    sa.Column('owner_name', sa.String(length=100), nullable=True, comment='域负责人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('phenomena',
    sa.Column('code', sa.String(length=30), nullable=False, comment='现象码，如 PH-IA-001'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='标准现象名称，如：中控屏显示异常'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('colloquial', sa.Text(), nullable=True, comment='客户口语说法，逗号分隔，如：黑屏,白屏,花屏,死机'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='现象分类，如：显示类/动力类/充电类'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_phenomena_name', 'phenomena', ['name'], unique=False)
    op.create_table('alm_requirements',
    sa.Column('req_no', sa.String(length=50), nullable=False, comment='需求编号，如 REQ-EV-0042'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='需求标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='需求描述'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级：P0/P1/P2/P3'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft/open/developing/verified/closed'),
    sa.Column('baseline_id', sa.BigInteger(), nullable=True, comment='目标基线'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['baseline_id'], ['alm_baselines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_no')
    )
    op.create_index('ix_alm_req_status', 'alm_requirements', ['status'], unique=False)
    op.create_table('root_causes',
    sa.Column('code', sa.String(length=30), nullable=False, comment='根因编码，如 RC-EV-0012'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='根因名称'),
    sa.Column('domain_id', sa.BigInteger(), nullable=True, comment='责任域 ID'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('description', sa.Text(), nullable=True, comment='根因描述'),
    sa.Column('cause', sa.Text(), nullable=True, comment='成因机理'),
    sa.Column('prevent', sa.Text(), nullable=True, comment='预防措施'),
    sa.Column('fix_way', sa.Text(), nullable=True, comment='处置方式，逗号分隔'),
    sa.Column('fix_duration', sa.String(length=100), nullable=True, comment='处置周期，如：2-5个工作日'),
    sa.Column('fix_success_rate', sa.String(length=50), nullable=True, comment='一次修复成功率，如：85%'),
    sa.Column('easy_hit', sa.Text(), nullable=True, comment='易发场景/车型/工况'),
    sa.Column('cost_money', sa.String(length=100), nullable=True, comment='单车处置成本区间'),
    sa.Column('verify_items', sa.Text(), nullable=True, comment='验证项，逗号分隔，如：读取BMS日志,测单体压差'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['domain_id'], ['owner_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_root_causes_domain', 'root_causes', ['domain_id'], unique=False)
    op.create_index('ix_root_causes_name', 'root_causes', ['name'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='平台登录名，与 ALM 平台一致'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('role_type', sa.String(length=20), nullable=False, comment='engineer/business/aftersales/customer/admin'),
    sa.Column('business_line', sa.String(length=10), nullable=True, comment='所属业务线（业务角色按此过滤）'),
    sa.Column('owner_domain_id', sa.BigInteger(), nullable=True, comment='所属责任域（工程师按此过滤）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_domain_id'], ['owner_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_role', 'users', ['role_type'], unique=False)
    op.create_table('alm_issues',
    sa.Column('issue_no', sa.String(length=50), nullable=False, comment='平台问题单号，如 ISS-2025-00123'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='问题标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题详述（客户投诉原文 / 工程师描述）'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源：engineer/business/aftersales/customer'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线：ev=电动化 / ia=智能化'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='严重度：blocker/critical/normal/minor'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：open/analyzing/fixing/verified/closed'),
    sa.Column('model_code', sa.String(length=50), nullable=True, comment='车型代号（脱敏后），如 EV-A01'),
    sa.Column('sw_version', sa.String(length=50), nullable=True, comment='软件版本，如 2024.32.5'),
    sa.Column('vin', sa.String(length=32), nullable=True, comment='车架号（脱敏，仅留后 6 位）'),
    sa.Column('dtc_snapshot', sa.String(length=500), nullable=True, comment='上报时的 DTC 快照，逗号分隔'),
    sa.Column('reporter_id', sa.BigInteger(), nullable=True, comment='上报人'),
    sa.Column('owner_domain_id', sa.BigInteger(), nullable=True, comment='当前责任域'),
    sa.Column('external_ref', sa.String(length=100), nullable=True, comment='外部溯源，如 nhtsa:11512345'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_domain_id'], ['owner_domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_no')
    )
    op.create_index('ix_alm_issues_line_model', 'alm_issues', ['business_line', 'model_code'], unique=False)
    op.create_index('ix_alm_issues_owner', 'alm_issues', ['owner_domain_id'], unique=False)
    op.create_index('ix_alm_issues_status', 'alm_issues', ['status'], unique=False)
    op.create_table('cause_phenomena',
    sa.Column('cause_id', sa.BigInteger(), nullable=False, comment='根因 ID'),
    sa.Column('phenomenon_id', sa.BigInteger(), nullable=False, comment='现象 ID'),
    sa.Column('weight', sa.Float(), nullable=False, comment='关联强度 0~1，写入 Neo4j INDICATES.weight'),
    sa.Column('is_core', sa.Boolean(), nullable=False, comment='是否该根因的核心（独有）现象'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['cause_id'], ['root_causes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phenomenon_id'], ['phenomena.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cause_id', 'phenomenon_id', name='uq_cause_phenomenon')
    )
    op.create_index('ix_cp_cause', 'cause_phenomena', ['cause_id'], unique=False)
    op.create_index('ix_cp_phenomenon', 'cause_phenomena', ['phenomenon_id'], unique=False)
    op.create_table('ai_triage_results',
    sa.Column('source_issue_id', sa.BigInteger(), nullable=True, comment='来源问题单'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='会话 ID（对应 Redis triage_state key）'),
    sa.Column('raw_input', sa.Text(), nullable=True, comment='用户原始描述'),
    sa.Column('confirmed_phenomena', sa.Text(), nullable=True, comment='已确认现象 JSON 数组'),
    sa.Column('denied_phenomena', sa.Text(), nullable=True, comment='已否认现象 JSON 数组'),
    sa.Column('candidate_causes', sa.Text(), nullable=True, comment='候选根因 Top-N JSON（含 confidence / 证据链）'),
    sa.Column('primary_cause_code', sa.String(length=30), nullable=True, comment='首要根因编码'),
    sa.Column('primary_confidence', sa.Float(), nullable=False, comment='首要根因置信度'),
    sa.Column('suggest_domain_id', sa.BigInteger(), nullable=True, comment='建议责任域'),
    sa.Column('total_rounds', sa.Integer(), nullable=False, comment='追问轮次'),
    sa.Column('force_conclude', sa.Boolean(), nullable=False, comment='是否轮次耗尽强制收敛'),
    sa.Column('adopted', sa.Boolean(), nullable=True, comment='人工是否采纳（None=未反馈），准确率统计口径'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['alm_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggest_domain_id'], ['owner_domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_triage_issue', 'ai_triage_results', ['source_issue_id'], unique=False)
    op.create_index('ix_triage_session', 'ai_triage_results', ['session_id'], unique=False)
    op.create_table('alm_change_requests',
    sa.Column('cr_no', sa.String(length=50), nullable=False, comment='变更单号，如 CR-2025-0088'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='变更标题'),
    sa.Column('reason', sa.Text(), nullable=True, comment='变更原因'),
    sa.Column('scope_desc', sa.Text(), nullable=True, comment='变更范围自然语言描述（LLM 解析入口）'),
    sa.Column('business_line', sa.String(length=10), nullable=False, comment='业务线'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：submitted/reviewing/approved/rejected/done'),
    sa.Column('target_baseline_id', sa.BigInteger(), nullable=True, comment='目标基线'),
    sa.Column('source_issue_id', sa.BigInteger(), nullable=True, comment='触发该变更的问题单'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['alm_issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_baseline_id'], ['alm_baselines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cr_no')
    )
    op.create_index('ix_alm_cr_status', 'alm_change_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alm_cr_status', table_name='alm_change_requests')
    op.drop_table('alm_change_requests')
    op.drop_index('ix_triage_session', table_name='ai_triage_results')
    op.drop_index('ix_triage_issue', table_name='ai_triage_results')
    op.drop_table('ai_triage_results')
    op.drop_index('ix_cp_phenomenon', table_name='cause_phenomena')
    op.drop_index('ix_cp_cause', table_name='cause_phenomena')
    op.drop_table('cause_phenomena')
    op.drop_index('ix_alm_issues_status', table_name='alm_issues')
    op.drop_index('ix_alm_issues_owner', table_name='alm_issues')
    op.drop_index('ix_alm_issues_line_model', table_name='alm_issues')
    op.drop_table('alm_issues')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_root_causes_name', table_name='root_causes')
    op.drop_index('ix_root_causes_domain', table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index('ix_alm_req_status', table_name='alm_requirements')
    op.drop_table('alm_requirements')
    op.drop_index('ix_phenomena_name', table_name='phenomena')
    op.drop_table('phenomena')
    op.drop_table('owner_domains')
    op.drop_index('ix_dtc_line', table_name='dtc_codes')
    op.drop_table('dtc_codes')
    op.drop_index('ix_alm_ci_safety', table_name='alm_config_items')
    op.drop_index('ix_alm_ci_module', table_name='alm_config_items')
    op.drop_table('alm_config_items')
    op.drop_index('ix_alm_baseline_frozen', table_name='alm_baselines')
    op.drop_table('alm_baselines')
    # ### end Alembic commands ###
