"""add alm_event_log

Revision ID: e28f1f434097
Revises: 72d5a060be9c
Create Date: 2026-07-26 22:55:05.154188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28f1f434097'
down_revision: Union[str, Sequence[str], None] = '72d5a060be9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alm_event_log',
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型：issue.created / issue.updated / issue.closed'),
    sa.Column('entity_type', sa.String(length=30), nullable=False, comment='实体类型：alm_issues / alm_requirements'),
    sa.Column('entity_id', sa.String(length=100), nullable=False, comment='平台侧实体 ID，如 ISS-2025-00123'),
    sa.Column('entity_version', sa.Integer(), nullable=False, comment='平台侧版本号，防重复投递'),
    sa.Column('payload_json', sa.Text(), nullable=True, comment='原始事件 JSON（审计/回放用）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'entity_type', 'entity_id', 'entity_version', name='uq_event_idempotent')
    )
    op.create_index('ix_event_entity', 'alm_event_log', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_entity', table_name='alm_event_log')
    op.drop_table('alm_event_log')
    # ### end Alembic commands ###
