"""add_cause_dtc_and_ai_shadow_tables

Revision ID: eeaf3ad1511d
Revises: 5983b791b2be
Create Date: 2026-07-28 11:08:58.830494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeaf3ad1511d'
down_revision: Union[str, Sequence[str], None] = '5983b791b2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cause_dtc',
    sa.Column('cause_id', sa.BigInteger(), nullable=False, comment='根因 ID'),
    sa.Column('dtc_id', sa.BigInteger(), nullable=False, comment='DTC 故障码 ID'),
    sa.Column('relation_type', sa.String(length=20), nullable=False, comment='关联类型：direct=直接指向 / indirect=间接关联'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['cause_id'], ['root_causes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dtc_id'], ['dtc_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cause_id', 'dtc_id', name='uq_cause_dtc')
    )
    op.create_index('ix_cd_cause', 'cause_dtc', ['cause_id'], unique=False)
    op.create_index('ix_cd_dtc', 'cause_dtc', ['dtc_id'], unique=False)
    op.create_table('ai_report_interpretations',
    sa.Column('source_issue_id', sa.BigInteger(), nullable=True, comment='来源问题单 ID'),
    sa.Column('report_type', sa.String(length=30), nullable=False, comment='报告类型：DTC扫描/台架测试/OTA回归'),
    sa.Column('minio_key', sa.String(length=200), nullable=True, comment='MinIO 附件路径'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='原始报告文本'),
    sa.Column('parsed_metrics', sa.Text(), nullable=True, comment='解析指标 JSON [{metric_key, value, unit, normal, severity}]'),
    sa.Column('abnormal_count', sa.Integer(), nullable=False, comment='异常指标数'),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='LLM 生成的结构化解读'),
    sa.Column('reviewed', sa.Boolean(), nullable=True, comment='人工复核结果'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_issue_id'], ['alm_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_issue', 'ai_report_interpretations', ['source_issue_id'], unique=False)
    op.create_index('ix_report_type', 'ai_report_interpretations', ['report_type'], unique=False)
    op.create_table('ai_impact_analysis',
    sa.Column('change_request_id', sa.BigInteger(), nullable=True, comment='来源变更单 ID'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='会话 ID'),
    sa.Column('raw_input', sa.Text(), nullable=True, comment='用户原始输入'),
    sa.Column('scope_result', sa.Text(), nullable=True, comment='影响范围 JSON'),
    sa.Column('dependency_result', sa.Text(), nullable=True, comment='依赖冲突 JSON'),
    sa.Column('baseline_conflicts', sa.Text(), nullable=True, comment='基线冲突 JSON'),
    sa.Column('duplicate_result', sa.Text(), nullable=True, comment='重复变更 JSON'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='风险等级：low/medium/high/critical'),
    sa.Column('report_md', sa.Text(), nullable=True, comment='Markdown 分析报告'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['change_request_id'], ['alm_change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_impact_cr', 'ai_impact_analysis', ['change_request_id'], unique=False)
    op.create_index('ix_impact_session', 'ai_impact_analysis', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_impact_session', table_name='ai_impact_analysis')
    op.drop_index('ix_impact_cr', table_name='ai_impact_analysis')
    op.drop_table('ai_impact_analysis')
    op.drop_index('ix_report_type', table_name='ai_report_interpretations')
    op.drop_index('ix_report_issue', table_name='ai_report_interpretations')
    op.drop_table('ai_report_interpretations')
    op.drop_index('ix_cd_dtc', table_name='cause_dtc')
    op.drop_index('ix_cd_cause', table_name='cause_dtc')
    op.drop_table('cause_dtc')
    # ### end Alembic commands ###
